### ISSUE TITLE
Problems if build_workdir/configure fails

### ISSUE THREAD

**Issue by omarandlorraine** [Kytech/rpi-zero-minimal-buildroot#1]
The script redirects stdout and stderr to /dev/null, and does not handle, or even report, errors.

(My git config by default does something duff with line endings, because of windows interoperability nonsense I have to deal with, so I get this error:

    /bin/bash: /home/sam/rpi-zero-minimal-buildroot/buildroot/support/scripts/setlocalversion: /bin/sh^M: bad interpreter: No such file or directory 

I appreciate my case is ... unique).

But it would be nice if the configure script at least showed me this or reported that the invocation of make failed. Do you have an opinion on what the right thing to do is here?

**Comment by Kytech** [comment]
Looks like the script can't run because the CRLF line endings break the shebang line, so that script hasn't even started executing. You will want to update the git settings for this repository to only to use lf line endings, then force a re-checkout. That can be done by running these commands in the root of the repo:

```
git config core.autocrlf false
git config core.eol lf
git checkout-index --force --all
```
You may also have to repeat those commands in the `buildroot` folder of the repository if that doesn't work since it's a git submodule.

If that doesn't work, you can always re-clone the repo with lf line endings explicitly specified with the following command:

```
git clone --recurse-submodules -c core.autocrlf=false -c core.eol=lf
```
Older git versions use `--recurse` or `--recursive` (can't remember off the top of my head) instead of `--recurse-submodules`.

That will make sure that line endings are cloned as lf, which should eliminate the error you experienced.

Regarding the configure script redirecting stderr, I believe I did that because you get a lot of warnings or verbose output that was either irrelevant or not applicable to that stage of the process. You're always welcome to delete that redirection if you need to, but in your case, that script isn't even running because of your line ending issues. That script couldn't report or handle any errors at all with improper line endings because the kernel gets thrown off when reading the shebang with CRLF line endings, even if it had additional error handling logic setup.

**Comment by Kytech** [comment]
@omarandlorraine any updates on if this fixed your issue? I'll probably close this due to inactivity since I'm pretty confident this is an issue with how your git setup handled line endings, unless I hear back indicating that this did not fix the issue.

**Comment by omarandlorraine** [comment]
Apologies for the late reply!

You were absolutely right, and I have it working as it should now. Thanks for helping me out.
