### ISSUE TITLE
Adding RPM packages

### ISSUE THREAD

**Issue by erfg12** [Kytech/rpi-zero-minimal-buildroot#2]
How can I install required libraries like SDL? If I can't, how should I setup wi-fi on my Pi 0 W board?

**Comment by Kytech** [comment]
> How can I install required libraries like SDL?

Are you referring to libraries required to build the image or libraries required for the application you want to run that are not in the image presently?

I'm going to venture a guess that it's the latter since I don't recall needing libraries like SDL to build the image, just the regular buildroot dependencies, but if it is a build dependency, those are usually just installed with your system package manager.

If it's a library you need to add, you'll want to add the buildroot package using buildroot's tools. If any of those have extra build dependencies to install on your system, they usually are documented by the packages. If there's no buildroot package, you'd either need to write one or use buildroot's features that let you add files to the image, since I think the built rootfs image may be configured for a read-only filesystem (though you can reconfigure that with the buildroot scripts of needed) and does not create a separate data-only partition. Most common libraries like SDL should have buildroot packages already available - the custom package or adding files to the rootfs would be most relevant if you have code of your own to load into the image.

> If I can't, how should I setup wi-fi on my Pi 0 W board?

To do that, you'll need to enable the kernel modules that the pi zero w needs in the kernel config and then add any other buildroot packages needed to provide networking services and tools that you need (pretty sure none of the networking commands and daemons like ping, ip/ifconfig, wpa_supplicant, etc. are present in the image as of right now)

**Comment by Kytech** [comment]
For some additional clarification, there is no package manager in the image that you flash to the Pi's SD card. You have to add everything to the build config and rebuild the image to add anything to it.

**Comment by Kytech** [comment]
> How can I install required libraries like SDL?

@erfg12 You can't install RPM packages into the SD card image produced by this buildroot config. I don't include a package manager in the build. You'd have to either find a buildroot package for the library and add it to the buildroot config, write a buildroot package and add it, or get a tarball for the library and use buildroot's features to copy over the tarball contents into the needed location as part of the build. Adding anything right now always has to be done as part of the build process of the SD card image.

I'm assuming these required dependencies refer to requirements you have for what you want to run on the pi, not to build the image, as I am pretty certain that this buildroot setup doesn't have additional dependencies for the system you use to build it on, other than what buildroot itself requires to run. Correct me if I'm wrong regarding the dependencies you are asking about.

> If I can't, how should I setup wi-fi on my Pi 0 W board?

To do that, you'll need to enable the kernel modules that the pi zero w needs in the kernel config and then add any other buildroot packages needed to provide networking services and tools that you need (pretty sure none of the networking commands and daemons like ping, ip/ifconfig, wpa_supplicant, etc. are present in the image as of right now)
